// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwvqlqjbbdtbgzjoedyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3dnFscWpiYmR0Ymd6am9lZHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTM1MzIsImV4cCI6MjA2MDYyOTUzMn0.4Jas29bSTUh2fqIocaYKdxO1meiU-mHzmRpJhZy-1n4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);